apiVersion: v1
kind: Service
metadata:
  name: week10-website
  namespace: week10-cicd
  labels:
    app: week10-website
spec:
  selector:
    app: week10-website
  ports:
  - port: 80
    targetPort: 80
  type: NodePort
