apiVersion: v1
kind: Service
metadata:
  name: week10-website
  namespace: week10-cicd
spec:
  type: NodePort
  selector:
    app: week10-website
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080